name: Test All Builds

permissions:
  contents: write
  actions: write

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Default Build (LineageOS)
          - name: LineageOS
            kernel_type: LineageOS

            susfs_support: true
            bbg_support: true
            susfs_force: false

          # NothingOSS Build
          - name: NothingOSS
            kernel_type: NothingOSS
            kernel_repo: https://github.com/NothingOSS/android_kernel_msm-5.10_nothing_sm8475.git
            kernel_branch: sm8475/b/mr
            kernel_defconfig: gki_defconfig
            extra_configs: vendor/waipio_GKI.config
            susfs_branch: gki-android13-5.10

            susfs_support: true
            bbg_support: true
            susfs_force: false

          # arter97 Build
          - name: arter97
            kernel_type: arter97
            kernel_repo: https://github.com/arter97/android_kernel_nothing_sm8475
            kernel_branch: master
            kernel_defconfig: /defconfig
            extra_patches_dir: patches/arter97

            susfs_support: true
            bbg_support: false
            susfs_force: false

    uses: ./.github/workflows/build.yml
    with:
      kernel_type: ${{ matrix.kernel_type }}
      kernel_repo: ${{ matrix.kernel_repo || '' }}
      kernel_branch: ${{ matrix.kernel_branch || 'lineage-23.2' }}
      kernel_defconfig: ${{ matrix.kernel_defconfig || 'gki_defconfig' }}
      extra_configs: ${{ matrix.extra_configs || '' }}
      extra_patches_dir: ${{ matrix.extra_patches_dir || '' }}
      susfs_support: ${{ matrix.susfs_support }}
      bbg_support: ${{ matrix.bbg_support }}
      susfs_force: ${{ matrix.susfs_force }}